### ISSUE TITLE
为啥使用minikube的ip访问不到

### ISSUE THREAD

**Issue by boteman0206** [guangzhengli/k8s-tutorials#86]
<img width="651" alt="image" src="https://user-images.githubusercontent.com/45304914/228820061-faa1b3bd-cb5c-435f-8ec5-2eac88d8994d.png">

**Comment by ShyunnY** [comment]
You should check how the service is mapped, or check your system's ip configuration.

**Comment by guangzhengli** [comment]
请参考 https://github.com/guangzhengli/k8s-tutorials/issues/5
