### ISSUE TITLE
docker build 命令报错

### ISSUE THREAD

**Issue by GOptimistic** [guangzhengli/k8s-tutorials#89]
您好，我在执行docker build . -t guangzhengli/hellok8s:v1这句命令时（已将用户名替换），报了如下错误
[+] Building 0.1s (4/4) FINISHED                                                                                                            
 => [internal] load .dockerignore                                                                                                      0.0s
 => => transferring context: 2B                                                                                                        0.0s
 => [internal] load build definition from Dockerfile                                                                                   0.0s
 => => transferring dockerfile: 359B                                                                                                   0.0s
 => CANCELED [internal] load metadata for gcr.io/distroless/base-debian10:latest                                                       0.1s
 => ERROR [internal] load metadata for docker.io/library/golang:1.16-buster                                                            0.1s
------
 > [internal] load metadata for docker.io/library/golang:1.16-buster:
------
Dockerfile:2
--------------------
   1 |     # Dockerfile
   2 | >>> FROM golang:1.16-buster AS builder
   3 |     RUN mkdir /src
   4 |     ADD . /src
--------------------
ERROR: failed to solve: golang:1.16-buster: encountered unknown type text/html; children may not be fetched

我安装的docker版本是23.0.2
不知道是不是版本的问题，想请您帮忙看一下

**Comment by guangzhengli** [comment]
目前我本地环境还是正常工作，你可以试一试直接 docker pull golang:1.16-buster 看看是否正常 work

**Comment by GOptimistic** [comment]
拉取之后正常work了，应该是仓库配置没有更新，非常感谢！
